/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    DatePickerBar: typeof import('./src/components/datepicker-bar/DatePickerBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TimePickerBar: typeof import('./src/components/timepicker-bar/TimePickerBar.vue')['default']
  }
}
